### ISSUE TITLE
Feature: User can view a list of recipes

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the drop down menu and select a health label. A list of recipes that match the health-label will appear below. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-03-04 at 8 43 40 PM](https://github.com/connie-chin/front-end-project/assets/155609517/cea9e62e-7c92-411c-8a49-dd4077673cc2)

![Screenshot 2024-03-04 at 8 53 42 PM](https://github.com/connie-chin/front-end-project/assets/155609517/dfea747b-43bd-443b-a055-16f028cd49c3)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Create an HTML for icons and header
- [x] Create HTML for the form that holds the drop down menu, and will hold the recipe hits that match the health-label provided. 
- [x] Write CSS for mobile devices first
- [x] Adjust styling CSS to adapt to changes to desktop. 
- [ ] Make the input from the user on the drop down required? it would be a click event
- [x] Add an input event listener to the dropdown select element 
- [x] make HTML to display the recipes, will delete later
- [x] create a dom tree for all the recipes to be displayed 
- [x] delete HTML recipes structure
- [x] add a submit event listener to the magnifying glass icon that will display all the recipes below 
- [x] understand the api and how it works, maybe a diff endpoint per diet and just choose to display those matching the diet. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
