### ISSUE TITLE
Design Update: Change color and round photos on cards

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/front-end-project#13]
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] use colorable to find color scheme AAA or AA large
- [x] round photo corners on cards

- **Clean Up**
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
