### ISSUE TITLE
Design Update: fix layout

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/front-end-project#15]
## ⚙️ Feature

> ##### Which feature is affected by this update?

## 📐 Plan

> ##### Summary of the technical approach to be taken.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![Screenshot 2024-08-12 at 1 47 25 PM](https://github.com/user-attachments/assets/1f7c85b7-0d02-492a-b251-e0cdb5883ca9)
![Screenshot 2024-08-12 at 1 51 01 PM](https://github.com/user-attachments/assets/7397c74c-df6b-417d-8184-393c7454d49f)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] adjust width of content container
- [x] 4 cards on desktop, with more space between
- [x] 1 card on mobile 
- [x] on mobile, stack search boxes
- [x] on mobile, make the search button bar same width as search boxes
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
