### ISSUE TITLE
Design Update: responsiveness, emoji size, search button, save button

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/front-end-project#17]
## ⚙️ Feature

> ##### Which feature is affected by this update?

## 📐 Plan

> ##### Summary of the technical approach to be taken.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] adjust card sizes uniformly
- [x] make sure layout is good. mobile and desktop responsiveness
- [x] fix emoji size with mobile and desktop
- [ ] make save button full width
- [ ] save button changes color when saved 
- [ ] search button turns a darker blue instead of transform
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
