### ISSUE TITLE
Feature: User can save recipes

### ISSUE THREAD

**Issue by connie-chin** [connie-chin/front-end-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Allow user to mouseover a recipe and save it for future viewing. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-03-07 at 9 26 17 AM](https://github.com/connie-chin/front-end-project/assets/155609517/608d8386-de0a-4e3c-ae6b-bf66a80316cb)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [x] add a save button to each recipe card when mouse is hovered over it
- [ ] adjust mouse cursor on the dialog to be a pointer as well
- [x] click event on the card and when saved is clicked, look for next li
- [x] look for closest li to the click event (saved button)
- [x] query first p which is a label
- [x] -if its equal to the label, loop through the array w the objects api?, if the label is equal to p, push the data at [i] into the object in data.ts dataObject.visited
- [x] test to see if the info got pushed into dataObject.visited
- [x]  call a function that creates dom functon for recipes favorites (we dont want it to be generated from api anymore, just the recipes we want saved
- [x] some viewswapping to see the saved recipes?(but this might be feature3)
- [x] make the home button one that refreshes the page or brings you back to empty home view?
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
